/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[i 0721 11:05:52.075372 20 __init__.py:227] Total mem: 251.73GB, using 16 procs for compiling.
[i 0721 11:06:10.862829 20 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:06:14.281083 20 init.cc:62] Found cuda archs: [75,]
[i 0721 11:06:14.471460 20 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:06:14.742093 20 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x34/AMDEPYC750232-x2a/default/cu11.0.221_sm_75/custom_ops
[i 0721 11:06:16.713125 80 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0721 11:06:16.748698 80 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0721 11:06:16.748777 80 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x34/AMDEPYC750232-x2a/default
[i 0721 11:06:16.785587 80 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0721 11:06:16.815739 80 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0721 11:06:17.012572 80 compiler.py:1011] cuda key:cu11.0.221_sm_75
[i 0721 11:06:17.570348 80 __init__.py:227] Total mem: 251.73GB, using 16 procs for compiling.
[i 0721 11:06:17.892038 80 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:06:21.065203 80 init.cc:62] Found cuda archs: [75,]
[i 0721 11:06:21.313295 80 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:06:21.758594 16 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0721 11:06:21.785133 16 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0721 11:06:21.785215 16 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x34/AMDEPYC750232-x2a/default
[i 0721 11:06:21.810763 16 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0721 11:06:21.835916 16 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0721 11:06:22.014838 16 compiler.py:1011] cuda key:cu11.0.221_sm_75
[i 0721 11:06:22.549907 16 __init__.py:227] Total mem: 251.73GB, using 16 procs for compiling.
[i 0721 11:06:22.838896 16 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:06:26.013335 16 init.cc:62] Found cuda archs: [75,]
[i 0721 11:06:26.246614 16 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:06:26.635228 28 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0721 11:06:26.661528 28 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0721 11:06:26.661601 28 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x34/AMDEPYC750232-x2a/default
[i 0721 11:06:26.687454 28 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0721 11:06:26.712292 28 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0721 11:06:26.907003 28 compiler.py:1011] cuda key:cu11.0.221_sm_75
[i 0721 11:06:27.489410 28 __init__.py:227] Total mem: 251.73GB, using 16 procs for compiling.
[i 0721 11:06:27.765345 28 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:06:30.939506 28 init.cc:62] Found cuda archs: [75,]
[i 0721 11:06:31.158332 28 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:06:31.628646 20 compile_extern.py:339] Downloading cutt...
[i 0721 11:06:31.791898 20 compile_extern.py:352] installing cutt...
[i 0721 11:06:44.555782 16 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x34/AMDEPYC750232-x2a/default/cu11.0.221_sm_75/cuda
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 5, in <module>
    from jseg.ops import resize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/__init__.py", line 1, in <module>
    from .backbones import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/__init__.py", line 1, in <module>
    from .mix_transformer import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/mix_transformer.py", line 4, in <module>
    from jseg.utils.helpers import to_2tuple
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/__init__.py", line 1, in <module>
    from .logger import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/logger.py", line 5, in <module>
    from tensorboardX import SummaryWriter
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
ModuleNotFoundError: No module named 'tensorboardX'
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 5, in <module>
    from jseg.ops import resize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/__init__.py", line 1, in <module>
    from .backbones import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/__init__.py", line 1, in <module>
    from .mix_transformer import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/mix_transformer.py", line 4, in <module>
    from jseg.utils.helpers import to_2tuple
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/__init__.py", line 1, in <module>
    from .logger import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/logger.py", line 5, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 5, in <module>
    from jseg.ops import resize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/__init__.py", line 1, in <module>
    from .backbones import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/__init__.py", line 1, in <module>
    from .mix_transformer import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/mix_transformer.py", line 4, in <module>
    from jseg.utils.helpers import to_2tuple
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/__init__.py", line 1, in <module>
    from .logger import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/logger.py", line 5, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 5, in <module>
    from jseg.ops import resize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/__init__.py", line 1, in <module>
    from .backbones import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/__init__.py", line 1, in <module>
    from .mix_transformer import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/mix_transformer.py", line 4, in <module>
    from jseg.utils.helpers import to_2tuple
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/__init__.py", line 1, in <module>
    from .logger import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/logger.py", line 5, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26) of binary: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/bin/python
Traceback (most recent call last):
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-21_11:07:05
  host      : ae01116-176624.0-aisurrey08.surrey.ac.uk
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 27)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-07-21_11:07:05
  host      : ae01116-176624.0-aisurrey08.surrey.ac.uk
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 28)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-07-21_11:07:05
  host      : ae01116-176624.0-aisurrey08.surrey.ac.uk
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 29)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-21_11:07:05
  host      : ae01116-176624.0-aisurrey08.surrey.ac.uk
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 26)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
