/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[i 0721 11:09:15.995769 00 __init__.py:227] Total mem: 251.74GB, using 16 procs for compiling.
[i 0721 11:09:39.523827 00 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:09:43.605212 00 init.cc:62] Found cuda archs: [75,]
[i 0721 11:09:43.729185 00 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:09:43.907521 00 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb0/AMDEPYC750232-x2a/default/cu11.0.221_sm_75/custom_ops
[i 0721 11:09:46.312385 32 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0721 11:09:46.343517 32 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0721 11:09:46.343607 32 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb0/AMDEPYC750232-x2a/default
[i 0721 11:09:46.373977 32 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0721 11:09:46.404319 32 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0721 11:09:46.630705 32 compiler.py:1011] cuda key:cu11.0.221_sm_75
[i 0721 11:09:47.278713 32 __init__.py:227] Total mem: 251.74GB, using 16 procs for compiling.
[i 0721 11:09:47.639907 32 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:09:51.351947 32 init.cc:62] Found cuda archs: [75,]
[i 0721 11:09:51.550722 32 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:09:51.883705 56 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0721 11:09:51.917373 56 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0721 11:09:51.917462 56 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb0/AMDEPYC750232-x2a/default
[i 0721 11:09:51.946795 56 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0721 11:09:51.975770 56 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0721 11:09:52.199436 56 compiler.py:1011] cuda key:cu11.0.221_sm_75
[i 0721 11:09:52.853103 56 __init__.py:227] Total mem: 251.74GB, using 16 procs for compiling.
[i 0721 11:09:53.205237 56 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:09:57.453142 56 init.cc:62] Found cuda archs: [75,]
[i 0721 11:09:57.667508 56 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:09:58.025387 96 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0721 11:09:58.056156 96 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0721 11:09:58.056248 96 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb0/AMDEPYC750232-x2a/default
[i 0721 11:09:58.082741 96 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0721 11:09:58.108980 96 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0721 11:09:58.315961 96 compiler.py:1011] cuda key:cu11.0.221_sm_75
[i 0721 11:09:58.954463 96 __init__.py:227] Total mem: 251.74GB, using 16 procs for compiling.
[i 0721 11:09:59.293638 96 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:10:02.897642 96 init.cc:62] Found cuda archs: [75,]
[i 0721 11:10:03.028159 96 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:10:03.341545 00 compile_extern.py:339] Downloading cutt...
[i 0721 11:10:03.574638 00 compile_extern.py:352] installing cutt...
[i 0721 11:10:20.201598 00 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb0/AMDEPYC750232-x2a/default/cu11.0.221_sm_75/cuda
terminate called after throwing an instance of 'std::runtime_error'
  what():  [f 0721 11:10:36.015381 56 helper_cuda.h:128] CUDA error at /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor/extern/cuda/cudnn/src/cudnn_wrapper.cc:28  code=4( CUDNN_STATUS_INTERNAL_ERROR ) cudnnCreate(&cudnn_handle)
terminate called after throwing an instance of 'std::runtime_error'
  what():  [f 0721 11:10:36.016352 00 helper_cuda.h:128] CUDA error at /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor/extern/cuda/cudnn/src/cudnn_wrapper.cc:28  code=4( CUDNN_STATUS_INTERNAL_ERROR ) cudnnCreate(&cudnn_handle)
terminate called after throwing an instance of 'std::runtime_error'
  what():  [f 0721 11:10:36.018556 96 helper_cuda.h:128] CUDA error at /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor/extern/cuda/cudnn/src/cudnn_wrapper.cc:28  code=4( CUDNN_STATUS_INTERNAL_ERROR ) cudnnCreate(&cudnn_handle)
terminate called after throwing an instance of 'std::runtime_error'
  what():  [f 0721 11:10:36.340744 32 helper_cuda.h:128] CUDA error at /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor/extern/cuda/cudnn/src/cudnn_wrapper.cc:28  code=4( CUDNN_STATUS_INTERNAL_ERROR ) cudnnCreate(&cudnn_handle)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 26) of binary: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/bin/python
Traceback (most recent call last):
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-21_11:10:49
  host      : ae01116-176626.0-aisurrey02.surrey.ac.uk
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 27)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 27
[2]:
  time      : 2024-07-21_11:10:49
  host      : ae01116-176626.0-aisurrey02.surrey.ac.uk
  rank      : 2 (local_rank: 2)
  exitcode  : -6 (pid: 28)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 28
[3]:
  time      : 2024-07-21_11:10:49
  host      : ae01116-176626.0-aisurrey02.surrey.ac.uk
  rank      : 3 (local_rank: 3)
  exitcode  : -6 (pid: 29)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 29
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-21_11:10:49
  host      : ae01116-176626.0-aisurrey02.surrey.ac.uk
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 26)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 26
============================================================
