/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[i 0721 11:32:36.756733 28 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0721 11:32:55.869834 28 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:33:00.344467 28 init.cc:62] Found cuda archs: [86,]
[w 0721 11:33:00.445491 28 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0721 11:33:00.553344 28 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:33:00.869349 28 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x68/AMDEPYC753232-x73/default/cu11.0.221_sm_86/custom_ops
[i 0721 11:33:02.813541 32 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0721 11:33:02.846507 32 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0721 11:33:02.846586 32 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x68/AMDEPYC753232-x73/default
[i 0721 11:33:02.877123 32 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0721 11:33:02.903900 32 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0721 11:33:03.109114 32 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0721 11:33:03.674319 32 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0721 11:33:04.041693 32 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:33:07.114940 32 init.cc:62] Found cuda archs: [86,]
[w 0721 11:33:07.199494 32 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0721 11:33:07.287101 32 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:33:07.582052 36 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0721 11:33:07.608536 36 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0721 11:33:07.608609 36 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x68/AMDEPYC753232-x73/default
[i 0721 11:33:07.637117 36 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0721 11:33:07.664321 36 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0721 11:33:07.886548 36 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0721 11:33:08.460268 36 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0721 11:33:08.797117 36 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:33:11.965722 36 init.cc:62] Found cuda archs: [86,]
[w 0721 11:33:12.069930 36 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0721 11:33:12.197369 36 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:33:12.628798 48 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0721 11:33:12.662152 48 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0721 11:33:12.662240 48 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x68/AMDEPYC753232-x73/default
[i 0721 11:33:12.690785 48 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0721 11:33:12.718196 48 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0721 11:33:13.026865 48 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0721 11:33:13.615136 48 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0721 11:33:13.951941 48 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:33:17.398377 48 init.cc:62] Found cuda archs: [86,]
[w 0721 11:33:17.522883 48 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0721 11:33:17.649051 48 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:33:18.211996 28 compile_extern.py:339] Downloading cutt...
[i 0721 11:33:18.378497 28 compile_extern.py:352] installing cutt...
[i 0721 11:33:30.998566 28 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x68/AMDEPYC753232-x73/default/cu11.0.221_sm_86/cuda
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 5, in <module>
    from jseg.ops import resize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/__init__.py", line 5, in <module>
    from .segmentors import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/__init__.py", line 3, in <module>
    from .clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/clip_rc.py", line 10, in <module>
    from jseg.utils.tokenizer import tokenize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/tokenizer.py", line 153, in <module>
    _tokenizer = SimpleTokenizer()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/tokenizer.py", line 73, in __init__
    merges = gzip.open(bpe_path).read().decode("utf-8").split('\n')
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'bpe_simple_vocab_16e6.txt.gz'
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 5, in <module>
    from jseg.ops import resize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/__init__.py", line 5, in <module>
    from .segmentors import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/__init__.py", line 3, in <module>
    from .clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/clip_rc.py", line 10, in <module>
    from jseg.utils.tokenizer import tokenize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/tokenizer.py", line 153, in <module>
    _tokenizer = SimpleTokenizer()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/tokenizer.py", line 73, in __init__
    merges = gzip.open(bpe_path).read().decode("utf-8").split('\n')
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'bpe_simple_vocab_16e6.txt.gz'
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 5, in <module>
    from jseg.ops import resize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/__init__.py", line 5, in <module>
    from .segmentors import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/__init__.py", line 3, in <module>
    from .clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/clip_rc.py", line 10, in <module>
    from jseg.utils.tokenizer import tokenize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/tokenizer.py", line 153, in <module>
    _tokenizer = SimpleTokenizer()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/tokenizer.py", line 73, in __init__
    merges = gzip.open(bpe_path).read().decode("utf-8").split('\n')
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'bpe_simple_vocab_16e6.txt.gz'
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 5, in <module>
    from jseg.ops import resize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/__init__.py", line 5, in <module>
    from .segmentors import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/__init__.py", line 3, in <module>
    from .clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/clip_rc.py", line 10, in <module>
    from jseg.utils.tokenizer import tokenize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/tokenizer.py", line 153, in <module>
    _tokenizer = SimpleTokenizer()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/tokenizer.py", line 73, in __init__
    merges = gzip.open(bpe_path).read().decode("utf-8").split('\n')
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'bpe_simple_vocab_16e6.txt.gz'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26) of binary: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/bin/python
Traceback (most recent call last):
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-21_11:33:48
  host      : ae01116-176631.0-aisurrey15.surrey.ac.uk
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 27)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-07-21_11:33:48
  host      : ae01116-176631.0-aisurrey15.surrey.ac.uk
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 28)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-07-21_11:33:48
  host      : ae01116-176631.0-aisurrey15.surrey.ac.uk
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 29)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-21_11:33:48
  host      : ae01116-176631.0-aisurrey15.surrey.ac.uk
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 26)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
