/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[i 0721 11:48:28.306998 28 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0721 11:48:47.343263 28 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:48:51.850947 28 init.cc:62] Found cuda archs: [86,]
[w 0721 11:48:51.953745 28 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0721 11:48:52.061533 28 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:48:52.391704 28 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb0/AMDEPYC753232-x73/default/cu11.0.221_sm_86/custom_ops
[i 0721 11:48:54.299014 32 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0721 11:48:54.337033 32 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0721 11:48:54.337129 32 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb0/AMDEPYC753232-x73/default
[i 0721 11:48:54.369428 32 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0721 11:48:54.406656 32 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0721 11:48:54.624765 32 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0721 11:48:55.200396 32 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0721 11:48:55.575198 32 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:48:58.665112 32 init.cc:62] Found cuda archs: [86,]
[w 0721 11:48:58.760854 32 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0721 11:48:58.851793 32 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:48:59.169255 04 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0721 11:48:59.202106 04 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0721 11:48:59.202188 04 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb0/AMDEPYC753232-x73/default
[i 0721 11:48:59.232242 04 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0721 11:48:59.257302 04 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0721 11:48:59.473295 04 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0721 11:49:00.038875 04 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0721 11:49:00.393116 04 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:49:03.577607 04 init.cc:62] Found cuda archs: [86,]
[w 0721 11:49:03.677797 04 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0721 11:49:03.783833 04 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:49:04.129726 64 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0721 11:49:04.161901 64 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0721 11:49:04.162044 64 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb0/AMDEPYC753232-x73/default
[i 0721 11:49:04.198364 64 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0721 11:49:04.234244 64 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0721 11:49:04.461454 64 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0721 11:49:05.053629 64 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0721 11:49:05.461260 64 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:49:08.518719 64 init.cc:62] Found cuda archs: [86,]
[w 0721 11:49:08.612603 64 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0721 11:49:08.719216 64 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:49:09.221861 28 compile_extern.py:339] Downloading cutt...
[i 0721 11:49:09.848628 28 compile_extern.py:352] installing cutt...
[i 0721 11:49:22.624799 04 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb0/AMDEPYC753232-x73/default/cu11.0.221_sm_86/cuda
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 15, in <module>
    class CLIPRC(EncoderDecoder):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/registry.py", line 10, in _register_module
    assert key not in self._modules, f"{key} is already registered."
Traceback (most recent call last):
AssertionError: CLIPRC is already registered.
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 15, in <module>
    class CLIPRC(EncoderDecoder):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/registry.py", line 10, in _register_module
    assert key not in self._modules, f"{key} is already registered."
AssertionError: CLIPRC is already registered.
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 15, in <module>
    class CLIPRC(EncoderDecoder):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/registry.py", line 10, in _register_module
    assert key not in self._modules, f"{key} is already registered."
AssertionError: CLIPRC is already registered.
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 15, in <module>
    class CLIPRC(EncoderDecoder):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/registry.py", line 10, in _register_module
    assert key not in self._modules, f"{key} is already registered."
AssertionError: CLIPRC is already registered.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26) of binary: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/bin/python
Traceback (most recent call last):
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-21_11:49:40
  host      : ae01116-176634.0-aisurrey15.surrey.ac.uk
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 27)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-07-21_11:49:40
  host      : ae01116-176634.0-aisurrey15.surrey.ac.uk
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 28)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-07-21_11:49:40
  host      : ae01116-176634.0-aisurrey15.surrey.ac.uk
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 29)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-21_11:49:40
  host      : ae01116-176634.0-aisurrey15.surrey.ac.uk
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 26)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
