/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[i 0725 13:23:43.997603 80 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0725 13:24:02.831359 80 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0725 13:24:06.530488 80 init.cc:62] Found cuda archs: [86,]
[w 0725 13:24:06.640353 80 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0725 13:24:06.763556 80 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0725 13:24:07.108756 80 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x90/AMDEPYC753232-x73/default/cu11.0.221_sm_86/custom_ops
[i 0725 13:24:09.101028 68 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0725 13:24:09.127766 68 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0725 13:24:09.127838 68 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x90/AMDEPYC753232-x73/default
[i 0725 13:24:09.153920 68 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0725 13:24:09.179603 68 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0725 13:24:09.363936 68 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0725 13:24:09.900474 68 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0725 13:24:10.256752 68 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0725 13:24:13.519516 68 init.cc:62] Found cuda archs: [86,]
[w 0725 13:24:13.627375 68 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0725 13:24:13.738244 68 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0725 13:24:14.174392 48 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0725 13:24:14.207938 48 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0725 13:24:14.208011 48 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x90/AMDEPYC753232-x73/default
[i 0725 13:24:14.245016 48 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0725 13:24:14.277531 48 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0725 13:24:14.483728 48 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0725 13:24:15.058123 48 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0725 13:24:15.419896 48 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0725 13:24:18.633234 48 init.cc:62] Found cuda archs: [86,]
[w 0725 13:24:18.751460 48 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0725 13:24:18.882525 48 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0725 13:24:19.346124 16 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0725 13:24:19.378438 16 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0725 13:24:19.378508 16 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x90/AMDEPYC753232-x73/default
[i 0725 13:24:19.411321 16 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0725 13:24:19.443885 16 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0725 13:24:19.642851 16 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0725 13:24:20.200431 16 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0725 13:24:20.581654 16 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0725 13:24:23.827789 16 init.cc:62] Found cuda archs: [86,]
[w 0725 13:24:23.960300 16 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0725 13:24:24.084131 16 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0725 13:24:25.052699 80 compile_extern.py:339] Downloading cutt...
[i 0725 13:24:26.176378 80 compile_extern.py:352] installing cutt...
[i 0725 13:24:40.718512 68 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x90/AMDEPYC753232-x73/default/cu11.0.221_sm_86/cuda
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 15, in <module>
    @SEGMENTORS.register_module()
NameError: name 'SEGMENTORS' is not defined
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 15, in <module>
    @SEGMENTORS.register_module()
NameError: name 'SEGMENTORS' is not defined
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 15, in <module>
    @SEGMENTORS.register_module()
NameError: name 'SEGMENTORS' is not defined
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 15, in <module>
    @SEGMENTORS.register_module()
NameError: name 'SEGMENTORS' is not defined
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26) of binary: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/bin/python
Traceback (most recent call last):
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-25_13:25:01
  host      : ae01116-177396.0-aisurrey11.surrey.ac.uk
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 27)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-07-25_13:25:01
  host      : ae01116-177396.0-aisurrey11.surrey.ac.uk
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 28)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-07-25_13:25:01
  host      : ae01116-177396.0-aisurrey11.surrey.ac.uk
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 29)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-25_13:25:01
  host      : ae01116-177396.0-aisurrey11.surrey.ac.uk
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 26)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
