/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[i 0725 14:51:29.523364 72 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0725 14:51:49.605513 72 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0725 14:51:53.501677 72 init.cc:62] Found cuda archs: [86,]
[w 0725 14:51:53.615791 72 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0725 14:51:53.736659 72 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0725 14:51:54.075055 72 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xda/AMDEPYC753232-x73/default/cu11.0.221_sm_86/custom_ops
[i 0725 14:51:56.123710 20 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0725 14:51:56.152086 20 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0725 14:51:56.152164 20 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xda/AMDEPYC753232-x73/default
[i 0725 14:51:56.181590 20 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0725 14:51:56.210415 20 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0725 14:51:56.410316 20 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0725 14:51:56.978606 20 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0725 14:51:57.323856 20 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0725 14:52:00.598913 20 init.cc:62] Found cuda archs: [86,]
[w 0725 14:52:00.710283 20 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0725 14:52:00.822180 20 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0725 14:52:01.250228 52 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0725 14:52:01.281446 52 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0725 14:52:01.281524 52 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xda/AMDEPYC753232-x73/default
[i 0725 14:52:01.313807 52 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0725 14:52:01.344742 52 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0725 14:52:01.539132 52 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0725 14:52:02.134894 52 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0725 14:52:02.491278 52 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0725 14:52:05.773639 52 init.cc:62] Found cuda archs: [86,]
[w 0725 14:52:05.884125 52 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0725 14:52:05.995884 52 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0725 14:52:06.362765 32 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0725 14:52:06.389431 32 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0725 14:52:06.389508 32 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xda/AMDEPYC753232-x73/default
[i 0725 14:52:06.417941 32 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0725 14:52:06.446034 32 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0725 14:52:06.654116 32 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0725 14:52:07.210380 32 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0725 14:52:07.553886 32 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0725 14:52:10.839171 32 init.cc:62] Found cuda archs: [86,]
[w 0725 14:52:10.947600 32 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0725 14:52:11.056789 32 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0725 14:52:11.691832 72 compile_extern.py:339] Downloading cutt...
[i 0725 14:52:11.926405 72 compile_extern.py:352] installing cutt...
[i 0725 14:52:26.629907 52 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xda/AMDEPYC753232-x73/default/cu11.0.221_sm_86/cuda
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 18, in <module>
    from models.backbone.clip_encoder_rlb import CLIPVisionTransformerWithRLB
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/backbone/clip_encoder_rlb.py", line 12, in <module>
    class CLIPVisionTransformerWithRLB(nn.Module):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/registry.py", line 10, in _register_module
    assert key not in self._modules, f"{key} is already registered."
AssertionError: CLIPVisionTransformerWithRLB is already registered.
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 18, in <module>
    from models.backbone.clip_encoder_rlb import CLIPVisionTransformerWithRLB
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/backbone/clip_encoder_rlb.py", line 12, in <module>
    class CLIPVisionTransformerWithRLB(nn.Module):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/registry.py", line 10, in _register_module
    assert key not in self._modules, f"{key} is already registered."
AssertionError: CLIPVisionTransformerWithRLB is already registered.
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 18, in <module>
    from models.backbone.clip_encoder_rlb import CLIPVisionTransformerWithRLB
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/backbone/clip_encoder_rlb.py", line 12, in <module>
    class CLIPVisionTransformerWithRLB(nn.Module):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/registry.py", line 10, in _register_module
    assert key not in self._modules, f"{key} is already registered."
AssertionError: CLIPVisionTransformerWithRLB is already registered.
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 18, in <module>
    from models.backbone.clip_encoder_rlb import CLIPVisionTransformerWithRLB
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/backbone/clip_encoder_rlb.py", line 12, in <module>
    class CLIPVisionTransformerWithRLB(nn.Module):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/registry.py", line 10, in _register_module
    assert key not in self._modules, f"{key} is already registered."
AssertionError: CLIPVisionTransformerWithRLB is already registered.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26) of binary: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/bin/python
Traceback (most recent call last):
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-25_14:52:45
  host      : ae01116-177435.0-aisurrey17.surrey.ac.uk
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 27)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-07-25_14:52:45
  host      : ae01116-177435.0-aisurrey17.surrey.ac.uk
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 28)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-07-25_14:52:45
  host      : ae01116-177435.0-aisurrey17.surrey.ac.uk
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 29)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-25_14:52:45
  host      : ae01116-177435.0-aisurrey17.surrey.ac.uk
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 26)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
