[i 0801 12:14:01.267733 24 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0801 12:14:19.888859 24 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0801 12:14:20.045438 24 init.cc:62] Found cuda archs: [86,]
[w 0801 12:14:20.130495 24 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0801 12:14:21.469836 24 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0801 12:14:21.551003 24 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xeb/AMDEPYC753232-x73/default/cu11.0.221_sm_86/custom_ops
[i 0801 12:14:23.586931 24 compile_extern.py:339] Downloading cutt...
[i 0801 12:14:23.736677 24 compile_extern.py:352] installing cutt...
[i 0801 12:14:35.923981 24 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xeb/AMDEPYC753232-x73/default/cu11.0.221_sm_86/cuda
[i 0801 12:14:52.332334 24 cuda_flags.cc:49] CUDA enabled.
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 83, in <module>
    main()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 62, in main
    torch.cuda.set_device(args.local_rank)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/cuda/__init__.py", line 309, in set_device
    device = _get_device_index(device)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/cuda/_utils.py", line 34, in _get_device_index
    return _torch_get_device_index(device, optional, allow_cpu)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/_utils.py", line 513, in _get_device_index
    raise ValueError('Expected a torch.device with a specified index '
ValueError: Expected a torch.device with a specified index or an integer, but got:None
