/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[i 0801 11:07:43.529776 40 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0801 11:07:43.534043 40 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0801 11:07:43.534113 40 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x90/AMDEPYC753232-x73/default
[i 0801 11:07:43.539110 40 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0801 11:07:43.544115 40 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0801 11:07:43.680791 40 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0801 11:07:44.251660 40 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0801 11:07:49.610321 40 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0801 11:07:49.801641 40 init.cc:62] Found cuda archs: [86,]
[w 0801 11:07:49.881905 40 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0801 11:07:51.077544 40 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0801 11:07:51.605254 20 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0801 11:07:51.609786 20 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0801 11:07:51.609856 20 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x90/AMDEPYC753232-x73/default
[i 0801 11:07:51.615878 20 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0801 11:07:51.620616 20 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0801 11:07:51.760046 20 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0801 11:07:52.238493 20 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0801 11:07:52.441117 20 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0801 11:07:52.578815 20 init.cc:62] Found cuda archs: [86,]
[w 0801 11:07:52.655303 20 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0801 11:07:53.882009 20 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0801 11:08:22.135023 24 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0801 11:08:22.140674 24 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0801 11:08:22.140746 24 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x90/AMDEPYC753232-x73/default
[i 0801 11:08:22.146864 24 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0801 11:08:22.153460 24 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0801 11:08:22.310152 24 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0801 11:08:22.802945 24 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0801 11:08:22.975146 24 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0801 11:08:23.121992 24 init.cc:62] Found cuda archs: [86,]
[w 0801 11:08:23.195724 24 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0801 11:08:24.517396 24 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0801 11:08:52.341131 56 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0801 11:08:52.347368 56 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0801 11:08:52.347447 56 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x90/AMDEPYC753232-x73/default
[i 0801 11:08:52.353485 56 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0801 11:08:52.359562 56 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0801 11:08:52.508643 56 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0801 11:08:52.981946 56 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0801 11:08:53.151107 56 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0801 11:08:53.277721 56 init.cc:62] Found cuda archs: [86,]
[w 0801 11:08:53.348054 56 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0801 11:08:54.472949 56 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0801 11:17:07.803828 40 cuda_flags.cc:49] CUDA enabled.
[i 0801 11:17:33.690740 20 cuda_flags.cc:49] CUDA enabled.
[i 0801 11:17:34.190784 24 cuda_flags.cc:49] CUDA enabled.
[i 0801 11:18:04.756266 56 cuda_flags.cc:49] CUDA enabled.

Compiling Operators(9/16) used:  3.4s eta: 2.64s Compiling Operators(13/16) used:  4.4s eta: 1.01s Compiling Operators(16/16) used:  5.4s eta:    0s 

Compiling Operators(3/4) used: 3.36s eta: 1.12s Compiling Operators(4/4) used: 4.36s eta:    0s 

Compiling Operators(1/2) used: 3.37s eta: 3.37s Compiling Operators(2/2) used: 4.37s eta:    0s 
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/losses/cross_entropy_loss.py:55: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with Jittor official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/losses/cross_entropy_loss.py:55: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with Jittor official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/losses/cross_entropy_loss.py:55: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with Jittor official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/losses/cross_entropy_loss.py:55: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with Jittor official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(

Compiling Operators(6/6) used: 4.35s eta:    0s 

Compiling Operators(1/5) used: 2.47s eta: 9.88s Compiling Operators(4/5) used: 3.47s eta: 0.868s Compiling Operators(5/5) used: 4.47s eta:    0s 

Compiling Operators(3/3) used: 4.34s eta:    0s 

Compiling Operators(3/3) used: 4.32s eta:    0s 
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 83, in <module>
    main()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 72, in main
    runner = Runner()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/runner/runner.py", line 51, in __init__
    self.train_dataset = build_from_cfg(cfg.dataset.train,
AttributeError: 'NoneType' object has no attribute 'train'
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 28 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 29 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 27) of binary: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/bin/python
Traceback (most recent call last):
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-01_11:25:24
  host      : ae01116-178645.0-aisurrey19.surrey.ac.uk
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 27)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
