/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[i 0806 21:33:28.114286 28 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0806 21:33:46.670266 28 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0806 21:33:46.845597 28 init.cc:62] Found cuda archs: [86,]
[w 0806 21:33:46.921042 28 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0806 21:33:48.037908 28 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0806 21:33:48.120906 28 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb5/AMDEPYC753232-x73/default/cu11.0.221_sm_86/custom_ops
[i 0806 21:33:50.056057 00 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0806 21:33:50.060897 00 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0806 21:33:50.060969 00 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb5/AMDEPYC753232-x73/default
[i 0806 21:33:50.066359 00 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0806 21:33:50.071470 00 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0806 21:33:50.209968 00 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0806 21:33:50.716957 00 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0806 21:33:50.888335 00 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0806 21:33:51.000783 00 init.cc:62] Found cuda archs: [86,]
[w 0806 21:33:51.075042 00 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0806 21:33:52.183707 00 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0806 21:33:52.381485 48 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0806 21:33:52.386511 48 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0806 21:33:52.386585 48 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb5/AMDEPYC753232-x73/default
[i 0806 21:33:52.393022 48 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0806 21:33:52.398391 48 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0806 21:33:52.541469 48 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0806 21:33:53.026104 48 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0806 21:33:53.215727 48 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0806 21:33:53.316155 48 init.cc:62] Found cuda archs: [86,]
[w 0806 21:33:53.385127 48 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0806 21:33:54.486478 48 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0806 21:33:54.613611 88 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0806 21:33:54.618197 88 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0806 21:33:54.618268 88 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb5/AMDEPYC753232-x73/default
[i 0806 21:33:54.623007 88 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0806 21:33:54.627640 88 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0806 21:33:54.765816 88 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0806 21:33:55.266239 88 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0806 21:33:55.447813 88 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0806 21:33:55.546157 88 init.cc:62] Found cuda archs: [86,]
[w 0806 21:33:55.618017 88 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0806 21:33:56.724658 88 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0806 21:33:57.137911 28 compile_extern.py:339] Downloading cutt...
[i 0806 21:33:57.970544 28 compile_extern.py:352] installing cutt...
[i 0806 21:34:11.282808 00 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb5/AMDEPYC753232-x73/default/cu11.0.221_sm_86/cuda
[i 0806 21:34:33.137231 48 cuda_flags.cc:49] CUDA enabled.
[i 0806 21:34:33.137304 28 cuda_flags.cc:49] CUDA enabled.
[i 0806 21:34:33.194524 00 cuda_flags.cc:49] CUDA enabled.
[i 0806 21:34:33.207756 88 cuda_flags.cc:49] CUDA enabled.

Compiling Operators(1/16) used: 2.51s eta: 37.7s Compiling Operators(9/16) used: 3.51s eta: 2.73s Compiling Operators(13/16) used: 4.51s eta: 1.04s Compiling Operators(16/16) used: 5.51s eta:    0s 

Compiling Operators(3/4) used: 3.32s eta: 1.11s Compiling Operators(4/4) used: 4.32s eta:    0s 

Compiling Operators(1/2) used: 3.31s eta: 3.31s Compiling Operators(2/2) used: 4.31s eta:    0s 
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/losses/cross_entropy_loss.py:55: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with Jittor official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/losses/cross_entropy_loss.py:55: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with Jittor official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/losses/cross_entropy_loss.py:55: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with Jittor official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/losses/cross_entropy_loss.py:55: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with Jittor official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(

Compiling Operators(6/6) used: 4.41s eta:    0s 

Compiling Operators(4/5) used: 3.36s eta: 0.841s Compiling Operators(5/5) used: 4.36s eta:    0s 

Compiling Operators(3/3) used: 4.34s eta:    0s 

Compiling Operators(3/3) used: 4.33s eta:    0s 

Compiling Operators(4/4) used: 4.34s eta:    0s 
[e 0806 21:35:15.199039 28 log.cc:258] Caught SIGINT, quick exit
[e 0806 21:35:15.296089 48 log.cc:258] Caught SIGINT, quick exit
[e 0806 21:35:15.431740 00 log.cc:258] Caught SIGINT, quick exit
[e 0806 21:35:15.599237 88 log.cc:258] Caught SIGINT, quick exit
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 25) of binary: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/bin/python
Traceback (most recent call last):
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-06_21:35:16
  host      : ae01116-179848.0-aisurrey12.surrey.ac.uk
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 26)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-08-06_21:35:16
  host      : ae01116-179848.0-aisurrey12.surrey.ac.uk
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 27)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-08-06_21:35:16
  host      : ae01116-179848.0-aisurrey12.surrey.ac.uk
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 28)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-06_21:35:16
  host      : ae01116-179848.0-aisurrey12.surrey.ac.uk
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 25)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
