/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py:183: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[i 0806 16:42:01.055541 40 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0806 16:42:19.802561 40 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0806 16:42:20.016837 40 init.cc:62] Found cuda archs: [86,]
[w 0806 16:42:20.092300 40 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0806 16:42:21.400569 40 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0806 16:42:21.475378 40 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x2f/AMDEPYC753232-x73/default/cu11.0.221_sm_86/custom_ops
[i 0806 16:42:23.385472 68 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0806 16:42:23.390725 68 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0806 16:42:23.390805 68 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x2f/AMDEPYC753232-x73/default
[i 0806 16:42:23.396867 68 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0806 16:42:23.402204 68 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0806 16:42:23.542272 68 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0806 16:42:24.044512 68 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0806 16:42:24.262344 68 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0806 16:42:24.450444 68 init.cc:62] Found cuda archs: [86,]
[w 0806 16:42:24.526181 68 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0806 16:42:25.844823 68 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0806 16:42:25.990630 72 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0806 16:42:25.995677 72 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0806 16:42:25.995749 72 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x2f/AMDEPYC753232-x73/default
[i 0806 16:42:26.001198 72 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0806 16:42:26.008034 72 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0806 16:42:26.160049 72 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0806 16:42:26.642156 72 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0806 16:42:26.826864 72 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0806 16:42:26.999167 72 init.cc:62] Found cuda archs: [86,]
[w 0806 16:42:27.072599 72 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0806 16:42:28.421092 72 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0806 16:42:28.537801 36 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0806 16:42:28.542358 36 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0806 16:42:28.542427 36 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x2f/AMDEPYC753232-x73/default
[i 0806 16:42:28.547759 36 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0806 16:42:28.552804 36 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0806 16:42:28.708355 36 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0806 16:42:29.269844 36 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0806 16:42:29.445946 36 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0806 16:42:29.613168 36 init.cc:62] Found cuda archs: [86,]
[w 0806 16:42:29.684752 36 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0806 16:42:31.126390 36 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0806 16:42:31.657345 40 compile_extern.py:339] Downloading cutt...
[i 0806 16:42:33.115260 40 compile_extern.py:352] installing cutt...
[i 0806 16:42:47.068219 72 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x2f/AMDEPYC753232-x73/default/cu11.0.221_sm_86/cuda
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 3, in <module>
    from jseg.runner import Runner
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/__init__.py", line 1, in <module>
    from .backbones import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/__init__.py", line 1, in <module>
    from .mix_transformer import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/mix_transformer.py", line 4, in <module>
    from jseg.utils.helpers import to_2tuple
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/__init__.py", line 1, in <module>
    from .logger import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/logger.py", line 5, in <module>
    from tensorboardX import SummaryWriter
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 3, in <module>
    from jseg.runner import Runner
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/__init__.py", line 1, in <module>
    from .backbones import *
ModuleNotFoundError: No module named 'tensorboardX'
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/__init__.py", line 1, in <module>
    from .mix_transformer import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/mix_transformer.py", line 4, in <module>
    from jseg.utils.helpers import to_2tuple
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/__init__.py", line 1, in <module>
    from .logger import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/logger.py", line 5, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 3, in <module>
    from jseg.runner import Runner
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/__init__.py", line 1, in <module>
    from .backbones import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/__init__.py", line 1, in <module>
    from .mix_transformer import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/mix_transformer.py", line 4, in <module>
    from jseg.utils.helpers import to_2tuple
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/__init__.py", line 1, in <module>
    from .logger import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/logger.py", line 5, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 3, in <module>
    from jseg.runner import Runner
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/__init__.py", line 1, in <module>
    from .backbones import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/__init__.py", line 1, in <module>
    from .mix_transformer import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/mix_transformer.py", line 4, in <module>
    from jseg.utils.helpers import to_2tuple
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/__init__.py", line 1, in <module>
    from .logger import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/logger.py", line 5, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
E0806 16:43:04.048224 140622749410240 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 22) of binary: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/bin/python
Traceback (most recent call last):
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 198, in <module>
    main()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 194, in main
    launch(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 179, in launch
    run(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-06_16:43:04
  host      : ae01116-179792.0-aisurrey14.surrey.ac.uk
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 23)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-08-06_16:43:04
  host      : ae01116-179792.0-aisurrey14.surrey.ac.uk
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 24)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-08-06_16:43:04
  host      : ae01116-179792.0-aisurrey14.surrey.ac.uk
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 25)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-06_16:43:04
  host      : ae01116-179792.0-aisurrey14.surrey.ac.uk
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 22)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
