[i 0807 08:11:16.959044 80 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0807 08:11:41.349375 80 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0807 08:11:41.530446 80 init.cc:62] Found cuda archs: [86,]
[w 0807 08:11:41.648095 80 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0807 08:11:43.351252 80 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0807 08:11:43.431740 80 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x13/AMDEPYC753232-x73/default/cu11.0.221_sm_86/custom_ops
[i 0807 08:11:46.089133 80 compile_extern.py:339] Downloading cutt...
[i 0807 08:11:46.592003 80 compile_extern.py:352] installing cutt...
[i 0807 08:12:02.268678 80 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x13/AMDEPYC753232-x73/default/cu11.0.221_sm_86/cuda
[i 0807 08:12:25.615752 80 cuda_flags.cc:49] CUDA enabled.
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/general.py:169: UserWarning: /mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/configs/_base_rc_clip_/zero_voc12_20_512x512.py/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/configs/_base_rc_clip_/default_runtime.py is not exists
  warnings.warn(f"{file} is not exists")
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 90, in <module>
    main()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 72, in main
    init_cfg(args.config_file)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/config/config.py", line 150, in init_cfg
    _cfg.load_from_file(filename)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/config/config.py", line 110, in load_from_file
    cfg = Config._load_dict_from_file(filename)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/config/config.py", line 75, in _load_dict_from_file
    Config._load_dict_from_file(os.path.join(cfg_dir, bfn)))
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/config/config.py", line 63, in _load_dict_from_file
    cfg = Config._load_dict_from_file_no_base(filename)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/config/config.py", line 57, in _load_dict_from_file_no_base
    assert (False), "unsupported config type."
AssertionError: unsupported config type.
