/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[i 0806 16:56:00.045629 40 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0806 16:56:18.530927 40 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0806 16:56:18.711142 40 init.cc:62] Found cuda archs: [86,]
[w 0806 16:56:18.781296 40 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0806 16:56:19.951807 40 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0806 16:56:20.032525 40 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb1/AMDEPYC753232-x73/default/cu11.0.221_sm_86/custom_ops
[i 0806 16:56:21.891352 76 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0806 16:56:21.895754 76 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0806 16:56:21.895822 76 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb1/AMDEPYC753232-x73/default
[i 0806 16:56:21.900584 76 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0806 16:56:21.904997 76 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0806 16:56:22.042763 76 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0806 16:56:22.553536 76 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0806 16:56:22.733196 76 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0806 16:56:22.878515 76 init.cc:62] Found cuda archs: [86,]
[w 0806 16:56:22.947360 76 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0806 16:56:24.167641 76 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0806 16:56:24.341044 76 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0806 16:56:24.345723 76 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0806 16:56:24.345792 76 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb1/AMDEPYC753232-x73/default
[i 0806 16:56:24.351061 76 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0806 16:56:24.356870 76 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0806 16:56:24.489019 76 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0806 16:56:24.982440 76 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0806 16:56:25.161268 76 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0806 16:56:25.324292 76 init.cc:62] Found cuda archs: [86,]
[w 0806 16:56:25.410990 76 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0806 16:56:26.533201 76 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0806 16:56:26.671433 60 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0806 16:56:26.676220 60 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0806 16:56:26.676288 60 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb1/AMDEPYC753232-x73/default
[i 0806 16:56:26.681397 60 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0806 16:56:26.686560 60 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0806 16:56:26.819900 60 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0806 16:56:27.352207 60 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0806 16:56:27.545934 60 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0806 16:56:27.667741 60 init.cc:62] Found cuda archs: [86,]
[w 0806 16:56:27.736504 60 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0806 16:56:28.844780 60 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0806 16:56:29.239761 40 compile_extern.py:339] Downloading cutt...
[i 0806 16:56:29.835870 40 compile_extern.py:352] installing cutt...
[i 0806 16:56:42.229871 76 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb1/AMDEPYC753232-x73/default/cu11.0.221_sm_86/cuda
[i 0806 16:57:02.276434 60 cuda_flags.cc:49] CUDA enabled.
[i 0806 16:57:02.280217 76 cuda_flags.cc:49] CUDA enabled.
[i 0806 16:57:02.318431 76 cuda_flags.cc:49] CUDA enabled.
[i 0806 16:57:02.405766 40 cuda_flags.cc:49] CUDA enabled.
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 84, in <module>
    main()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 73, in main
    runner = Runner()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/runner/runner.py", line 21, in __init__
    assert (self.max_iter is None) ^ (
AssertionError: You must set max_iter or max_epoch
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 84, in <module>
    main()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 73, in main
    runner = Runner()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/runner/runner.py", line 21, in __init__
    assert (self.max_iter is None) ^ (
AssertionError: You must set max_iter or max_epoch
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 84, in <module>
    main()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 73, in main
    runner = Runner()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/runner/runner.py", line 21, in __init__
    assert (self.max_iter is None) ^ (
AssertionError: You must set max_iter or max_epoch
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 84, in <module>
    main()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 73, in main
    runner = Runner()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/runner/runner.py", line 21, in __init__
    assert (self.max_iter is None) ^ (
AssertionError: You must set max_iter or max_epoch
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26) of binary: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/bin/python
Traceback (most recent call last):
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-06_16:57:08
  host      : ae01116-179793.0-aisurrey14.surrey.ac.uk
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 27)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-08-06_16:57:08
  host      : ae01116-179793.0-aisurrey14.surrey.ac.uk
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 28)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-08-06_16:57:08
  host      : ae01116-179793.0-aisurrey14.surrey.ac.uk
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 29)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-06_16:57:08
  host      : ae01116-179793.0-aisurrey14.surrey.ac.uk
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 26)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
