python: can't open file '/path/to/test.py': [Errno 2] No such file or directory
Watching job link.sh
{'ok': True, 'result': {'message_id': 24, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1717953470, 'text': '----- Starting to watch the file -----'}}
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/link_telegram.py", line 34, in <module>
    old_content = open_file(file)
                  ^^^^^^^^^^^^^^^
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/link_telegram.py", line 21, in open_file
    with open(file, "r") as f:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/logs/clink.sh.p0.error'
Watching job link.sh
{'ok': True, 'result': {'message_id': 25, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1717953649, 'text': '----- Starting to watch the file -----'}}
{'ok': True, 'result': {'message_id': 26, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1717953650, 'text': 'Watching file /mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/logs/clink.sh.p0.error'}}
{'ok': True, 'result': {'message_id': 27, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1717953650, 'text': 'File /mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/logs/clink.sh.p0.error not found.'}}
{'ok': True, 'result': {'message_id': 28, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1717953650, 'text': 'The file is empty, stopping the watch.'}}
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/link_telegram.py", line 42, in <module>
    sleep(10)
    ^^^^^
NameError: name 'sleep' is not defined
Watching job 1908
{'ok': True, 'result': {'message_id': 29, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1717953678, 'text': '----- Starting to watch the file -----'}}
{'ok': True, 'result': {'message_id': 30, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1717953679, 'text': 'Watching file /mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/logs/c1908.p0.error'}}
{'ok': True, 'result': {'message_id': 31, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1717953679, 'text': 'File /mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/logs/c1908.p0.error not found.'}}
{'ok': True, 'result': {'message_id': 32, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1717953679, 'text': 'The file is empty, stopping the watch.'}}
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/link_telegram.py", line 42, in <module>
    sleep(10)
    ^^^^^
NameError: name 'sleep' is not defined
Watching job 0
{'ok': True, 'result': {'message_id': 33, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1717958602, 'text': '----- Starting to watch the file -----'}}
{'ok': True, 'result': {'message_id': 34, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1717958602, 'text': 'Watching file /mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/logs/c0.p0.error'}}
{'ok': True, 'result': {'message_id': 35, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1717958602, 'text': 'File /mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/logs/c0.p0.error not found.'}}
Watching job 170649
{'ok': True, 'result': {'message_id': 36, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1717958647, 'text': '----- Starting to watch the file -----'}}
{'ok': True, 'result': {'message_id': 37, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1717958647, 'text': 'Watching file /mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/logs/c170649.p0.error'}}
{'ok': True, 'result': {'message_id': 38, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1717958648, 'text': 'No new lines, stopping the watch.'}}
usage: link_telegram.py [-h] [--job JOB] [--type TYPE]
link_telegram.py: error: unrecognized arguments: 170650
Watching job 170878
{'ok': True, 'result': {'message_id': 247, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037496, 'text': '----- Starting to watch the file -----'}}
{'ok': True, 'result': {'message_id': 248, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037496, 'text': 'Watching file /mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/logs/c170878.p0.error'}}
{'ok': True, 'result': {'message_id': 249, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037516, 'text': 'Traceback (most recent call last):'}}
{'ok': True, 'result': {'message_id': 250, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037517, 'text': 'File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/zegenv/lib/python3.9/site-packages/PIL/Image.py", line 3130, in fromarray'}}
{'ok': True, 'result': {'message_id': 251, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037517, 'text': 'mode, rawmode = _fromarray_typemap[typekey]'}}
{'ok': True, 'result': {'message_id': 252, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037517, 'text': "KeyError: ((1, 1, 3), '<f4')"}}
{'ok': False, 'error_code': 400, 'description': 'Bad Request: message text is empty'}
{'ok': True, 'result': {'message_id': 253, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037517, 'text': 'The above exception was the direct cause of the following exception:'}}
{'ok': False, 'error_code': 400, 'description': 'Bad Request: message text is empty'}
{'ok': True, 'result': {'message_id': 254, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037517, 'text': 'Traceback (most recent call last):'}}
{'ok': True, 'result': {'message_id': 255, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037517, 'text': 'File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 194, in <module>', 'entities': [{'offset': 68, 'length': 8, 'type': 'url'}]}}
{'ok': True, 'result': {'message_id': 256, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037517, 'text': 'main()'}}
{'ok': True, 'result': {'message_id': 257, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037518, 'text': 'File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 182, in main', 'entities': [{'offset': 68, 'length': 8, 'type': 'url'}]}}
{'ok': True, 'result': {'message_id': 258, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037538, 'text': 'No new lines, stopping the watch.'}}
Watching job 170879
{'ok': True, 'result': {'message_id': 259, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037550, 'text': '----- Starting to watch the file -----'}}
{'ok': True, 'result': {'message_id': 260, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037550, 'text': 'Watching file /mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/logs/c170879.p0.error'}}
{'ok': True, 'result': {'message_id': 261, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037550, 'text': 'File /mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/logs/c170879.p0.error not found.'}}
Watching job 170879
{'ok': True, 'result': {'message_id': 262, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037556, 'text': '----- Starting to watch the file -----'}}
{'ok': True, 'result': {'message_id': 263, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037556, 'text': 'Watching file /mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/logs/c170879.p0.error'}}
{'ok': True, 'result': {'message_id': 264, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037576, 'text': 'fatal: not a git repository (or any parent up to mount point /scratch/condor)'}}
{'ok': True, 'result': {'message_id': 265, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037576, 'text': 'Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).'}}
{'ok': True, 'result': {'message_id': 266, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037576, 'text': '2024-06-10 16:39:21,948 - mmseg - INFO - Environment info:'}}
{'ok': True, 'result': {'message_id': 267, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037576, 'text': '------------------------------------------------------------'}}
{'ok': True, 'result': {'message_id': 268, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037576, 'text': 'sys.platform: linux'}}
{'ok': True, 'result': {'message_id': 269, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037577, 'text': 'Python: 3.9.19 (main, May  6 2024, 19:43:03) [GCC 11.2.0]'}}
{'ok': True, 'result': {'message_id': 270, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037577, 'text': 'CUDA available: True'}}
{'ok': True, 'result': {'message_id': 271, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037577, 'text': 'GPU 0: NVIDIA GeForce RTX 2080 Ti'}}
{'ok': True, 'result': {'message_id': 272, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037577, 'text': 'CUDA_HOME: /usr/local/cuda'}}
{'ok': True, 'result': {'message_id': 273, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037577, 'text': 'NVCC: Build cuda_11.0_bu.TC445_37.28845127_0'}}
{'ok': True, 'result': {'message_id': 274, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037577, 'text': 'GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0'}}
{'ok': True, 'result': {'message_id': 275, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037597, 'text': 'Traceback (most recent call last):'}}
{'ok': True, 'result': {'message_id': 276, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037597, 'text': 'File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/zegenv/lib/python3.9/site-packages/PIL/Image.py", line 3130, in fromarray'}}
{'ok': True, 'result': {'message_id': 277, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037598, 'text': 'mode, rawmode = _fromarray_typemap[typekey]'}}
{'ok': True, 'result': {'message_id': 278, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037598, 'text': "KeyError: ((1, 1, 256), '<f4')"}}
{'ok': False, 'error_code': 400, 'description': 'Bad Request: message text is empty'}
{'ok': True, 'result': {'message_id': 279, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037598, 'text': 'The above exception was the direct cause of the following exception:'}}
{'ok': False, 'error_code': 400, 'description': 'Bad Request: message text is empty'}
{'ok': True, 'result': {'message_id': 280, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037598, 'text': 'Traceback (most recent call last):'}}
{'ok': True, 'result': {'message_id': 281, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037598, 'text': 'File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 194, in <module>', 'entities': [{'offset': 68, 'length': 8, 'type': 'url'}]}}
{'ok': True, 'result': {'message_id': 282, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037599, 'text': 'main()'}}
{'ok': True, 'result': {'message_id': 283, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037599, 'text': 'File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 182, in main', 'entities': [{'offset': 68, 'length': 8, 'type': 'url'}]}}
{'ok': True, 'result': {'message_id': 284, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037619, 'text': 'No new lines, stopping the watch.'}}
Watching job 170880
{'ok': True, 'result': {'message_id': 285, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037658, 'text': '----- Starting to watch the file -----'}}
{'ok': True, 'result': {'message_id': 286, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037658, 'text': 'Watching file /mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/logs/c170880.p0.error'}}
{'ok': True, 'result': {'message_id': 287, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037678, 'text': 'fatal: not a git repository (or any parent up to mount point /scratch/condor)'}}
{'ok': True, 'result': {'message_id': 288, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037678, 'text': 'Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).'}}
{'ok': True, 'result': {'message_id': 289, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037678, 'text': '2024-06-10 16:41:03,537 - mmseg - INFO - Environment info:'}}
{'ok': True, 'result': {'message_id': 290, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037678, 'text': '------------------------------------------------------------'}}
{'ok': True, 'result': {'message_id': 291, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037679, 'text': 'sys.platform: linux'}}
{'ok': True, 'result': {'message_id': 292, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037679, 'text': 'Python: 3.9.19 (main, May  6 2024, 19:43:03) [GCC 11.2.0]'}}
{'ok': True, 'result': {'message_id': 293, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037679, 'text': 'CUDA available: True'}}
{'ok': True, 'result': {'message_id': 294, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037679, 'text': 'GPU 0: NVIDIA GeForce RTX 2080 Ti'}}
{'ok': True, 'result': {'message_id': 295, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037679, 'text': 'CUDA_HOME: /usr/local/cuda'}}
{'ok': True, 'result': {'message_id': 296, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037679, 'text': 'NVCC: Build cuda_11.0_bu.TC445_37.28845127_0'}}
{'ok': True, 'result': {'message_id': 297, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037679, 'text': 'GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0'}}
{'ok': True, 'result': {'message_id': 298, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037699, 'text': 'Traceback (most recent call last):'}}
{'ok': True, 'result': {'message_id': 299, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037699, 'text': 'File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/zegenv/lib/python3.9/site-packages/PIL/Image.py", line 3130, in fromarray'}}
{'ok': True, 'result': {'message_id': 300, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037700, 'text': 'mode, rawmode = _fromarray_typemap[typekey]'}}
{'ok': True, 'result': {'message_id': 301, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037700, 'text': "KeyError: ((1, 1, 3), '<f4')"}}
{'ok': False, 'error_code': 400, 'description': 'Bad Request: message text is empty'}
{'ok': True, 'result': {'message_id': 302, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037700, 'text': 'The above exception was the direct cause of the following exception:'}}
{'ok': False, 'error_code': 400, 'description': 'Bad Request: message text is empty'}
{'ok': True, 'result': {'message_id': 303, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037700, 'text': 'Traceback (most recent call last):'}}
{'ok': True, 'result': {'message_id': 304, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037701, 'text': 'File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 194, in <module>', 'entities': [{'offset': 68, 'length': 8, 'type': 'url'}]}}
{'ok': True, 'result': {'message_id': 305, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037701, 'text': 'main()'}}
{'ok': True, 'result': {'message_id': 306, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037701, 'text': 'File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 182, in main', 'entities': [{'offset': 68, 'length': 8, 'type': 'url'}]}}
{'ok': True, 'result': {'message_id': 307, 'from': {'id': 7298020171, 'is_bot': True, 'first_name': 'python-logs', 'username': 'python_logs_antoine_bot'}, 'chat': {'id': 6284547224, 'first_name': 'Antoine', 'last_name': 'Edy', 'type': 'private'}, 'date': 1718037721, 'text': 'No new lines, stopping the watch.'}}
